### PR TITLE
Issue template to push for direct collaboration

### PR DESCRIPTION
**Pull request by martinheidegger**
Currently the government is a bit unclear. This issue template should help clarify what issues are better as PR.

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Shouldn't we track issues in `Projects`?

**Comment by martinheidegger** [comment]
@AnshulMalik afaik. Only team members can add items to Projects. Issues can be added by the greater public. Issues that regard policy, such as #40, are rather theoretical without an actual suggestion on how to change the text. With this Issue template I wanted to point contributors
that PR's are better ways to discuss policy.

**Comment by martinheidegger** [comment]
@AnshulMalik  Can we merge this?

**Comment by AnshulMalik** [comment]
Yep looks good :)

**Pull request merged**
