### PR TITLE
add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by sethvincent**
Here's a first draft of a CONTRIBUTING.md file as discussed in #14 & #10.

It's based on the [node.js contributing guidelines](https://raw.githubusercontent.com/nodejs/node/master/CONTRIBUTING.md) and [openopensource.org](http://openopensource.org/).

Feel free to make changes on the contributing branch as needed.

### CODE REVIEW

**Review by martinheidegger — CHANGES_REQUESTED** [review]
Many sections in here still refer to the node foundation and Node.js or structure. Do you want to fix that before merging?

**Comment by llkats** [comment]
I'm planning on adding/editing some stuff tonight!

**Comment by sethvincent** [comment]
@martinheidegger ah sorry i missed some things

@llkats 👍 go ahead and push changes to the contributing branch.

**Comment by llkats** [comment]
Awesome start, @sethvincent! I removed a few more nodejs-specific things and added links to the gitter chatrooms.

A few questions:
- Who is in charge of specific workshoppers? I think we should designate maintainers ("stewards"?) in each workshopper's README so it's not overwhelming to maintain a bunch of workshoppers for a few people. We don't have to answer this question right this second, but might be nice to leave a note to fill this in later.
- Do we care that much about specifying commit message line character lengths and rebasing? I don't feel as stringent as Node core, so was wondering if people have thoughts on that?

**Comment by sethvincent** [comment]
Agreed, there should be a list of maintainers in the workshopper readme.

Yeah, it seems like the rebasing and commit message line character lengths can be removed.

**Comment by llkats** [comment]
@sethvincent @martinheidegger updated! What do you think? As a first draft, I think it's okay for publishing, barring any further edit requests.

**Comment by sethvincent** [comment]
Cool! Looks good to me.

**Review by martinheidegger — APPROVED** [review]

**Comment by martinheidegger** [comment]
Fixed NodeFoundation -> Workshopper org in on commit. Else LGTM. Took the honor of merging it ;)

**Pull request merged**
